#ifndef DISPLAY_CONSTS_H
#define DISPLAY_CONSTS_H

#include <stdint.h>

#define DISPLAY_SPI_FREQUENCY 75000000
#define DISPLAY_SPI_MODE 0

/// --- Display Commands ---

enum display_command_byte {
  NO_OPERATION = 0x00,
  SOFTWARE_RESET = 0x01,

  SLEEP_IN_MODE = 0x10,
  SLEEP_OUT_MODE = 0x11,

  PARTIAL_MODE = 0x12,
  NORMAL_MODE = 0x13,

  INVERT_OFF = 0x20,
  INVERT_ON = 0x21,

  DISPLAY_OFF = 0x28,
  DISPLAY_ON = 0x29,

  COLUMN_ADDRESS_SET = 0x2a,
  ROW_ADDRESS_SET = 0x2b,
  WRITE_RAM = 0x2c,

  PARTIAL_AREA_SET = 0x30,

  MEMORY_ACCESS_CONTROL = 0x36,

  IDLE_MODE_OFF = 0x38,
  IDLE_MODE_ON = 0x39,

  COLOUR_FORMAT_SET = 0x3a,

  WRITE_RAM_CONTINUE = 0x3c,

  DISPLAY_BRIGHTNESS_SET = 0x51,
  DISPLAY_BRIGHTNESS_CONTROL = 0x53,

  RAM_CONTROL = 0xb0,
};

#endif
